// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoeMais.Data;

#nullable disable

namespace VoeMais.Migrations
{
    [DbContext(typeof(VoeMaisContext))]
    partial class VoeMaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoeMais.Models.Aeroporto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoIATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aeroportos");
                });

            modelBuilder.Entity("VoeMais.Models.Aviao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaAereaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaAereaId");

                    b.ToTable("Avioes");
                });

            modelBuilder.Entity("VoeMais.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VoeMais.Models.EmpresaAerea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmpresasAereas");
                });

            modelBuilder.Entity("VoeMais.Models.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AeroportoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Chegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Partida")
                        .HasColumnType("datetime2");

                    b.Property<int>("VooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AeroportoId");

                    b.HasIndex("VooId");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("VoeMais.Models.Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("VooPoltronaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VooPoltronaId");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("VoeMais.Models.Poltrona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AviaoId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AviaoId");

                    b.ToTable("Poltronas");
                });

            modelBuilder.Entity("VoeMais.Models.Voo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AviaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Chegada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("OrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Partida")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AviaoId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigemId");

                    b.ToTable("Voos");
                });

            modelBuilder.Entity("VoeMais.Models.VooPoltrona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PoltronaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoltronaId");

                    b.HasIndex("VooId");

                    b.ToTable("VoosPoltronas");
                });

            modelBuilder.Entity("VoeMais.Models.Aviao", b =>
                {
                    b.HasOne("VoeMais.Models.EmpresaAerea", "EmpresaAerea")
                        .WithMany("Avioes")
                        .HasForeignKey("EmpresaAereaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaAerea");
                });

            modelBuilder.Entity("VoeMais.Models.Escala", b =>
                {
                    b.HasOne("VoeMais.Models.Aeroporto", "Aeroporto")
                        .WithMany()
                        .HasForeignKey("AeroportoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoeMais.Models.Voo", "Voo")
                        .WithMany("Escalas")
                        .HasForeignKey("VooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aeroporto");

                    b.Navigation("Voo");
                });

            modelBuilder.Entity("VoeMais.Models.Passagem", b =>
                {
                    b.HasOne("VoeMais.Models.Cliente", "Cliente")
                        .WithMany("Passagens")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoeMais.Models.VooPoltrona", "VooPoltrona")
                        .WithMany()
                        .HasForeignKey("VooPoltronaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("VooPoltrona");
                });

            modelBuilder.Entity("VoeMais.Models.Poltrona", b =>
                {
                    b.HasOne("VoeMais.Models.Aviao", "Aviao")
                        .WithMany("Poltronas")
                        .HasForeignKey("AviaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aviao");
                });

            modelBuilder.Entity("VoeMais.Models.Voo", b =>
                {
                    b.HasOne("VoeMais.Models.Aviao", "Aviao")
                        .WithMany("Voos")
                        .HasForeignKey("AviaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoeMais.Models.Aeroporto", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoeMais.Models.Aeroporto", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aviao");

                    b.Navigation("Destino");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("VoeMais.Models.VooPoltrona", b =>
                {
                    b.HasOne("VoeMais.Models.Poltrona", "Poltrona")
                        .WithMany()
                        .HasForeignKey("PoltronaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VoeMais.Models.Voo", "Voo")
                        .WithMany("Poltronas")
                        .HasForeignKey("VooId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poltrona");

                    b.Navigation("Voo");
                });

            modelBuilder.Entity("VoeMais.Models.Aviao", b =>
                {
                    b.Navigation("Poltronas");

                    b.Navigation("Voos");
                });

            modelBuilder.Entity("VoeMais.Models.Cliente", b =>
                {
                    b.Navigation("Passagens");
                });

            modelBuilder.Entity("VoeMais.Models.EmpresaAerea", b =>
                {
                    b.Navigation("Avioes");
                });

            modelBuilder.Entity("VoeMais.Models.Voo", b =>
                {
                    b.Navigation("Escalas");

                    b.Navigation("Poltronas");
                });
#pragma warning restore 612, 618
        }
    }
}
